name: Workflow for Codecov example-python
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Find hash
        id: hash
        uses: theowenyoung/folder-hash@v2.0.1
        with:
          path: |
            .
      - name: Copy a file from s3
        id: copy
        uses: prewk/s3-cp-action@v2
        continue-on-error: true
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          source: 's3://infra-prod-docs/hyperledger/iroha2/codecov/coverage-{{ steps.hash.outputs.hash }}.xml'
          dest: 'coverage.xml'
      - name: Check coverage file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "coverage.xml"
      - name: Debug
        run: ls -al .
      - name: Run tests and collect coverage
        if: steps.check_files.outputs.files_exists == 'false'
        run: pytest --cov app
      - name: Debug
        run: ls -al .
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
      - name: Copy a file to s3
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          source: 'coverage.xml'
          dest: 's3://infra-prod-docs/hyperledger/iroha2/codecov/coverage-{{ steps.hash.outputs.hash }}.xml'

