name: Workflow for Codecov example-python
on:   
  pull_request_target:
    branches: [main, support/1.*, edge, develop]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Find hash
        id: hash
        uses: theowenyoung/folder-hash@v2.0.1
        with:
          path: |
            .
